# version format
version: "{build}"

image: Visual Studio 2019
platform:
  - x64
configuration: release

clone_folder: C:\projects\PETPVC

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-5.2.0
  ITKBUILD: C:\projects\deps\ITK-BUILD

install:
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps
  - set ITK_URL="https://github.com/InsightSoftwareConsortium/ITK/archive/v5.2.0.zip"
  - IF NOT EXIST C:\projects\deps\ITK-5.2.0.zip appveyor DownloadFile %ITK_URL% -FileName ITK-5.2.0.zip
  - IF NOT EXIST %ITKINSTALL% ( 7z x ITK-5.2.0.zip -oC:\projects\deps\ITK > nul &&
      mkdir %ITKBUILD% &&
      cd %ITKBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=%ITKINSTALL% -DModule_ITKReview=ON ..\ITK\ITK-5.2.0 &&
      msbuild INSTALL.vcxproj
    )

cache:
  - C:\projects\deps\ITK-5.2.0.zip
  - C:\projects\deps\ITK-5.2.0 -> appveyor.yml

build_script:
  - cd C:\projects\PETPVC
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%ITKINSTALL% -DCMAKE_INSTALL_PATH=. .
  - msbuild INSTALL.vcxproj
  - msbuild RUN_TESTS.vcxproj
  - msbuild PACKAGE.vcxproj
  - ps: Get-ChildItem .\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
deploy:
  - provider: GitHub
    auth_token:
        secure: rAhVQ15Ngn/wGthOvIkrQqrMi9jEjFbKwSUan4OxblikIglipPmQTnzZUViYpbmw
    release: PETPVC-$(appveyor_build_version)
    description: 'Binary release - $(appveyor_build_version)'
    artifact: /.*\.exe/
    draft: true

